project:
  output-dir: _site
  render: 
    - "*.qmd"
    - "posts/"

lang: en-US

website:
  navbar:
    left:
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: books.qmd
        text: Book Review
      - href: robotics.qmd
        text: "Robotics & AI"

    right:
      - text: "FR"
        href: fr/index.html
      - icon: github
        href: https://github.com/oussou-dev
      - icon: linkedin
        href: https://linkedin.com/in/ousmanecisse

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, dark.scss]
    css: styles.css
    include-after-body: scripts/lang-switch.html
    toc: true
