project:
  output-dir: _site
  render: 
    - "fr/"

lang: fr-FR

website:
  navbar:
    left:
      - href: fr/projects.qmd
        text: Projets
      - href: fr/blog.qmd
        text: Blog
    right:
      - text: "EN"
        href: ../index.html
      - icon: github
        href: https://github.com/oussou-dev
      - icon: linkedin
        href: https://linkedin.com/in/ousmanecisse

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, dark.scss]
    css: styles.css
    toc: true
