project:
  type: website

execute:
  freeze: auto

lightbox: auto

profile:
  default: en
  group: [en, fr]

website:
  title: "OUSMANE CISSE"
  site-url: "https://oussou.dev"
  search: true
  back-to-top-navigation: true


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, dark.scss]
    css: styles.css
    toc: true
    include-after-body: scripts/lang-switch.html
    smooth-scroll: true
    link-external-newtab: true
    code-copy: true
    code-fold: show
    resources:
      - "assets"
      - "img"
      - "styles.css"
      - "scripts"
      - "CNAME"

filters:
  - filters/audio_player.lua
  - filters/metadata_to_meta.lua
  - filters/series_nav.lua
  - lightbox
  - code-fullscreen
