project:
  output-dir: _site
  render: 
    - "*.qmd"
    - "posts/"
    - "!fr/"

lang: en-US

website:
  navbar:
    left:
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
    right:
      - text: "FR"
        href: fr/index.html
      - icon: github
        href: https://github.com/oussou-dev
      - icon: linkedin
        href: https://linkedin.com/in/ousmanecisse

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, dark.scss]
    css: styles.css
    toc: true
