project:
  type: website

profile:
  default: en
  group: [en, fr]

website:
  title: "OUSMANE CISSE"
  search: true

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, dark.scss]
    css: styles.css
    toc: true
