llm:
  provider: gemini
  model: gemini-pro-latest
  temperature: 0.4

audio:
  short_duration: 90
  long_duration: 480
  default_engine: gtts
  voices:
    qwen:
      en: "Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice"
      fr: "Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice"
    # coqui:
    #   en: "tts_models/en/ljspeech/vits"
    #   fr: "tts_models/fr/css10/vits"

paths:
  posts_dir: posts
  audio_output: assets/audio
  transcripts_output: assets/transcripts
